import re
file = open("run4hackz.py","r")
txt = file.read()
file.close()
f = open("run4hackz.py","w")
path = input("Enter full path to file: ")
txt = re.sub(r"db.txt",path,txt)
f.truncate()
f.write(txt)
f.close()
print("Modified to phone version.")
input("Press any key to exit...")
